# Site wide configuration

title:           "Home-Zhenke Wu"
headtitle:       "Zhenke Wu, PhD"
description:     "Personal website of Zhenke Wu, PhD"
logo:            
teaser:          
locale:           en_US
url:              http://zhenkewu.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Zhenke Wu
  avatar: ZW.JPG
  bio: "Postdoctoral Fellow at Johns Hopkins Department of Biostatistics. "
  position: "Postdoctoral Fellow"
  department: "Department of Biostatistics"
  school: "Bloomberg School of Public Health"
  university: "Johns Hopkins University"
  email: zhenkewu@gmail.com
  email2: "zhwu@jhu.edu"
  navcolor: "#D91838"
  skype: wzk_qdh4
  disqus-shortname: zhenkewu
  twitter: zhenkewu
  facebook: zhenke.wu
  google:
    plus: 
    analytics: UA-57530925-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: zhenkewu
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
